# This config is for testing PredRNN++ on climate data
# WORK IN PROGRESS

output_dir: /Users/songhune/PycharmProjects/nesap-stl/outcomes/

trainer: auto_regressive

data:
    name: climate
    data_file: /Users/songhune/PycharmProjects/nesap-stl/data/tosna_data_1yravg.npy
    patch_size: 5 #원래 4인데 뭔지 모르겠음
    n_train: 14389
    n_valid: 2048
    seq_len: 16
    batch_size: 4

model:
    name: predrnn_pp
    num_hidden: [8, 16, 32, 16]
    #num_hidden: [128, 64, 64, 64, 16]

loss:
    name: MSELoss

optimizer:
    name: Adam
    lr: 0.001

train:
    n_epochs: 32
